import { BarChartOutlined, FileTextOutlined, PictureOutlined, SettingOutlined } from '@ant-design/icons'
import { Alert, Button, Card, Form, Input, Layout, Menu, Progress, Statistic, Table, Tag } from 'antd'
import { useState } from 'react'
import { FeatureUnavailable } from '../components/FeatureUnavailable'
import { PageMeta } from '../components/PageMeta'

const menu = [{ key: 'dashboard', icon: <BarChartOutlined />, label: '概览' }, { key: 'posts', icon: <FileTextOutlined />, label: '文章管理' }, { key: 'media', icon: <PictureOutlined />, label: '媒体库' }, { key: 'settings', icon: <SettingOutlined />, label: '站点设置' }]
function Shell({ section, children }: { section: string; children: React.ReactNode }) { return <Layout className="min-h-[640px] overflow-hidden rounded-xl border border-slate-200 bg-white"><Layout.Sider width={180} breakpoint="md"><Menu theme="dark" mode="inline" selectedKeys={[section]} items={menu} /></Layout.Sider><Layout.Content className="p-6">{children}</Layout.Content></Layout> }
export function AdminDashboard() { return <section><PageMeta title="后台概览" /><Shell section="dashboard"><h1 className="text-2xl font-bold">内容概览</h1><FeatureUnavailable feature="PV / UV 统计" detail="百度统计和站内 analytics API 尚未接入，指标卡不展示虚构数据。" /><div className="grid gap-4 md:grid-cols-3"><Card><Statistic title="文章总数" value="—" /></Card><Card><Statistic title="今日 PV" value="—" /></Card><Card><Statistic title="今日 UV" value="—" /></Card></div><Card title="部署状态" className="mt-5"><Alert message="等待云效与飞书 Webhook 接入" type="info" showIcon /></Card></Shell></section> }
export function AdminPosts() { return <section><PageMeta title="文章管理" /><Shell section="posts"><div className="mb-4 flex items-center justify-between"><h1 className="text-2xl font-bold">文章管理</h1><Button type="primary" href="/admin/editor">新建文章</Button></div><Table rowKey="id" pagination={false} dataSource={[]} columns={[{ title: '标题', dataIndex: 'title' }, { title: '状态', render: () => <Tag>草稿</Tag> }, { title: '更新时间', dataIndex: 'updatedAt' }, { title: '操作', render: () => <Button type="link">编辑</Button> }]} locale={{ emptyText: '暂无文章；需要管理员认证和文章管理 API 后展示数据' }} /></Shell></section> }
export function EditorPage() { const [text, setText] = useState('# 新文章\n\n开始写作…'); return <section><PageMeta title="编辑文章" /><Shell section="posts"><h1 className="text-2xl font-bold">Markdown 编辑器</h1><FeatureUnavailable feature="自动保存、图片上传与发布" detail="编辑器 UI 已准备；草稿保存、COS 预签名上传、分类/标签 API 与管理员鉴权尚待后端实现。" /><Form layout="vertical"><Form.Item label="标题"><Input placeholder="文章标题" /></Form.Item><Form.Item label="正文"><Input.TextArea value={text} onChange={e => setText(e.target.value)} rows={18} /></Form.Item><div className="flex gap-3"><Button>保存草稿</Button><Button type="primary">发布</Button></div></Form></Shell></section> }
export function MediaPage() { return <section><PageMeta title="媒体库" /><Shell section="media"><h1 className="text-2xl font-bold">媒体库</h1><FeatureUnavailable feature="腾讯云 COS 直传" detail="需要后端预签名 URL、文件类型/大小校验和 COS/CDN 凭证。当前不会上传文件到未知位置。" /><Card><Button disabled>选择文件上传</Button><Progress className="mt-5" percent={0} /></Card></Shell></section> }
export function SettingsPage() { return <section><PageMeta title="站点设置" /><Shell section="settings"><h1 className="text-2xl font-bold">站点设置</h1><Form layout="vertical" className="max-w-xl"><Form.Item label="站点名称"><Input defaultValue="CXJ Blog" /></Form.Item><Form.Item label="站点描述"><Input.TextArea defaultValue="记录思考，也分享实践。" /></Form.Item><Form.Item label="社交链接"><Input placeholder="https://github.com/..." /></Form.Item><Button type="primary" disabled>保存设置</Button></Form><p className="mt-3 text-sm text-slate-500">保存功能等待站点设置 API 与管理员权限接入。</p></Shell></section> }
